server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frame?useUnicode=true&useSSL=true&serverTimezone=UTC
    username: root
    password: zxc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  typeAliasesPackage: com.xin.demo.model
  mapperLocations: classpath:mapper/*.xml
